# Site settings
title: yog2-site
email: fex@.baidu.com
description: A Node.js UI Layer Framework Based on FIS & Express
baseurl: "/yog2" # the subpath of your site, e.g. /blog/
url: "http://fex-team.github.io/yog2" # the base hostname & protocol for your site
github_username: fex-team

# Build settings
markdown: kramdown
defaults:
  -
    scope:
      path: "docs"
      type: "pages"
    values:
      layout: "docs"
